name: ci

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: "./destination-iceberg-sql/Dockerfile_java"
          tags: dashbook/destination-iceberg:java-sql
          cache-from: type=registry,ref=dashbook/destination-iceberg:java-sql
          cache-to: type=inline
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: "./destination-iceberg-sql/Dockerfile_python"
          tags: dashbook/destination-iceberg:python-sql
          cache-from: type=registry,ref=dashbook/destination-iceberg:python-sql
          cache-to: type=inline
